### ISSUE TITLE
IsRowMaster not been called when immutableData set to ture

### ISSUE THREAD

**Issue by Nikerim** [ag-grid/ag-grid-enterprise#265] opened 2021-04-29 11:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After updating my immutable data, the grid does not refresh the master indication for existing rows that are now master

**Expected behavior**
Master indication will be prompt

**Comment by kiril-matev** [comment] 2022-09-07 17:08
Hi @Nikerim,

Thank you for reporting this.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

When submitting this issue, you have not followed the bug report template. Specifically, you've not included a live example reproducing the issue you've reported, you've not provided a list of steps to follow or a description of actual/expected behavior.

As it's been over a year since this issue was opened and many improvements were made to the grid in this period, please try to reproduce the issue with the latest version. If you're still seeing this bug with the latest version of AG Grid, please open a new issue in the main following the bug report template and providing a live plunker example reproducing this issue.

**We will close this issue now and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**

**Closed by kiril-matev** 2022-09-07 17:08 UTC
