### ISSUE TITLE
changing row height issue in ag grid version above 25

### ISSUE THREAD

**Issue by josephkuruvilla** [ag-grid/ag-grid-enterprise#262] opened 2021-03-10 07:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When clicking on the cell in the table, cell editor is not opening when we have onRowHeightChanged(). It's not working in when we upgraded the version to 25.1.0. below 24 it was working fine.
gridApi.api.forEachNode(rowNode => rowNode.rowIndex === index && rowNode.setRowHeight(height))
gridApi.api.onRowHeightChanged()
**Expected behavior**

when we click on the cell in the table, the cell editor will be open and if we type something based on the criteria it will show the error messages. If the error message is too long the row height will get changed automatically. Now onRowHeightChanged() is not working fine with version of 25.1.0
**Minimal reproduction of the problem with instructions**

1. Ag grid table with column defs
    const columnDefs = [
  {
    floatingFilter: true,
    headerName: 'Default Text',
    field: 'defaulttext',
    type: 'Default',
    editable: true,
    cellEditor: 'CellTextEditor',
    cellValidation: getValidation
  },....
]
2. Cell text editor component will have the text input component with all the methods.
3. When click on the cell, the cell editor will be open with input field. when type something in the input, based on the validation it will the display the error messages below to the input field. If the error is too long, it will increase the row height with the following functionality as per ag grid documentation. but onRowHeightChanged() is not working with the above version of 25. 

gridApi.api.forEachNode(rowNode => rowNode.rowIndex === index && rowNode.setRowHeight(height))
gridApi.api.onRowHeightChanged()

**Please tell us about your environment:**

windows 10, Visual studio code , NPM, localhost:4000

* **ag-Grid-Enterprise version:** 25.1.0

yes its the most recent recent version

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

yes all browsers are reproducing the same issue

* **Language:** [ES6/7 | ES5]

**Comment by kiril-matev** [comment] 2022-09-07 16:57
Hi @josephkuruvilla,

Thank you for opening this issue.

This issue was opened in a legacy repository which was not monitored and this is why we have not responded to this earlier. 

You've not followed the bug report format and you've not provided a live sample reproducing the issue. As a result, we're unable to reproduce this issue with the input you've provided. Also this issue is over a year old and many improvements have since been made to AG Grid specifically in row auto-height.

If you can still reproduce this issue with the latest version of AG Grid, please open a new issue in the main repo of AG Grid following the bug report template and providing a live example demonstrating the behavior. 

**We will close this issue now and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**

**Closed by kiril-matev** 2022-09-07 16:57 UTC
