### ISSUE TITLE
Not Equals filter operation not working with tree data Ag Grid(27.3.0)

### ISSUE THREAD

**Issue by VrushakKTR** [ag-grid/ag-grid-enterprise#296] opened 2022-09-06 09:15 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
As per the current functionality of Ag Grid Tree data, Columns are auto grouped by default. But few filter operations seems to be not working with the grouped data. Eg. Not Equal, Less than, Less Than Equals operators.

Equal, Greater Than , Greater Than Equal operators filters data as required.

Scenario :
**I have two columns (Year and Publication Name), Year column has a number filter and Publication name has text filter. Issue is with the filter operations for Year column. "Equal, Greater Than and Greater Than Equal" filter filters all the matching records correctly, but "Not Equal, Less Than, Less Than Equal" operator seems to be not filtering the records.**

**Expected behavior**
Operators "Not Equal", "Less than" , "Less Than Equals" should filter the records as expected for grouped records.

**Minimal reproduction of the problem with instructions**
Plunker created for the same.
https://plnkr.co/edit/UMyfMS5pz7Ez8nYT?open=app%2Fapp.component.ts

**Please tell us about your environment:**
Angular 9, , Windows 10

* **ag-Grid-Enterprise version:** 
Ag Grid 27.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by kiril-matev** [comment] 2022-09-07 11:24
Hi @VrushakKTR,

This is expected behavior because the group column value is converted to type string. You're using number filter on the group column which doesn't work with the string values in the group column.

We have added a feature request in our backlog to enhance grouping so it keeps the underlying value type in the group column.

You can track it with this reference:
**AG-5734 [Row Grouping] Allow keeping the type of the grouped column value instead of converting it to string**

You can follow the status of feature requests, bugs and releases using our pipeline:
https://www.ag-grid.com/ag-grid-pipeline/

**Now that this requirement is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this feature is added in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/**

Thanks again for bringing this up with us - we appreciate your time!

If you want to report any new issues, please report them under the main repository as this repository is legacy and will be deleted. This way you'll ensure any issues you submit will be processed promptly and seen by the entire AG Grid community.

**Closed** 2022-09-07 11:26 UTC
