### ISSUE TITLE
Warning message when opening Excel export

### ISSUE THREAD

**Issue by SamJBentley** [ag-grid/ag-grid-enterprise#176] opened 2018-04-16 12:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When I download an Excel export of the table and open it in Excel 2016, I get a warning message stating "The file format and extension of [file].xls don't match. The file could be corrupted or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?"

![excel_export](https://user-images.githubusercontent.com/19324577/38808482-48d09120-4178-11e8-88fd-88e1cbf43817.png)

If I select "yes", the file opens and behaves as expected, but to our users, this looks a bit buggy.

**Expected behavior**
A downloaded Excel file opens without warning messages.

**Minimal reproduction of the problem with instructions**
1. Using the table context menu, select Excel Export
2. Open the file using Excel 2016
3. Note the warning message

**What is the motivation / use case for changing the behavior?**
It looks buggy to our users

**Please tell us about your environment:**
Using Windows 7 and CDN as source of JS

* **ag-Grid-Enterprise version:** 2.0.X
13.3.1

* **Browser:** [Chrome 65]

* **Language:** [ES6/7]

**Comment by ITGuy9401** [comment] 2018-05-06 14:31
it happens to me too. And it's unable to open the file on Microsoft Excel Online, it says that it's unable to convert the file to a xlsx for opening it on Excel Online.

![image](https://user-images.githubusercontent.com/11537307/39674351-b3df17f2-514a-11e8-894b-4920733b73cb.png)

![image](https://user-images.githubusercontent.com/11537307/39674353-c7c60f3c-514a-11e8-9c96-fa84e9f0a667.png)

**Comment by mstroming** [comment] 2018-06-19 17:27
Same issue here. Any advice/workarounds from the Ag-Grid folks?

**Comment by aborchew** [comment] 2018-07-20 19:37
I've opened an Enterprise Support issue. The SheetJS example in the documentation works well if you don't need to include any styles in your output, but if that's the case it's only slightly more useful than a CSV.

Using the generated SheetJS output, I've been able to programmatically add back the number formatting that we were using, but in order to get SheetJS to export the cell styles that ag-grid does, we'd need to purchase a paid license to SheetJS.

Here is what our [ExcelService](https://codepen.io/aborchew/post/ag-grid-to-xls-without-warnings) looks like.

**Comment by vikasnawal** [comment] 2018-08-30 10:02
import * as _ from 'lodash';
import * as XLSX from 'xlsx';
import b64toBlob from 'b64-to-blob';
import { ExcelExportParams, GridOptions } from 'ag-grid';
import { Injectable } from '@angular/core';
import { VISUAL_CONFIG } from 'app/visual/base/visual.config';
import { Visualization } from 'app/visual/base/visualization.model';
import { VisualService } from 'app/visual/services/visual/visual.service';

@Injectable({
  providedIn: 'root'
})
export class ExcelService {

  private static readonly ExcelExportParamsDefaults: ExcelExportParams = {
    columnGroups: true,
    fileName: 'ag-grid.xls'
  }

  private static readonly ExcelExportParamsOverrides: ExcelExportParams = {
    suppressTextAsCDATA: true
  }

  public static gridToXLSXSheetJS (
    agGridOptions: GridOptions,
    agGridExportParams: ExcelExportParams
  ): void {

    const fileName = 'sheetjs.xlsx';
    const workbook = XLSX.read(agGridOptions.api.getDataAsExcel(agGridExportParams), { type: 'binary' });

    _.mapValues(workbook.Sheets['ag-grid'], val => {

      if (_.isObject(val)) {
        val.z = _.get(_.find(agGridOptions.excelStyles, { id: val.StyleID }), 'numberFormat.format');
      }

      return val;

    });

    const xlsxContent = XLSX.write(workbook, { bookType: 'xlsx', type: 'base64' });
    const blobObject = b64toBlob(xlsxContent, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

    if (window.navigator.msSaveOrOpenBlob) {
      window.navigator.msSaveOrOpenBlob(blobObject, fileName);
    } else {
      const downloadLink = document.createElement('a');
      downloadLink.href = URL.createObjectURL(blobObject);
      downloadLink.download = fileName;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
    }

  }

  public static gridToXLSXSheetAgGrid (
    agGridOptions: GridOptions,
    agGridExportParams: ExcelExportParams
  ): void {
    agGridOptions.api.exportDataAsExcel(agGridExportParams);
  }

  public static gridToXLXS (
    v: Visualization,
    agGridExportParams: ExcelExportParams = {}
  ): void {

    const agGridApi = _.get(v, 'options.apiRef.agGridOptions.api');
    const currentState = _.get(v, 'state.value');

    if (!agGridApi || !currentState) return;

    agGridExportParams = _.assignIn(ExcelService.ExcelExportParamsDefaults, agGridExportParams);
    agGridExportParams = _.assignIn(agGridExportParams, ExcelService.ExcelExportParamsOverrides);

    agGridExportParams.processCellCallback = agGridExportParams.processCellCallback || ((context) => {

      let value = _.clone(context.value);
      let column = _.get(context, 'column') && context.column.getColDef();

      if (context.node.rowPinned === 'top' && !context.value) {
        if (context.column.isPinnedLeft()) {
          return 'Totals';
        }
        value = context.node.data[column.field];
      }

      if (!value) return '';

      if (!column || column.cellRenderer === 'agGroupCellRenderer') {
        column = _.get(context, 'node.rowGroupColumn') && context.node.rowGroupColumn.getColDef();
      }

      const decoratedEnum = VisualService.enumFromCellClass(column.cellClass as string[]);

      if (decoratedEnum) {

        const visualDataType = _.find(VISUAL_CONFIG.VISUAL_DATA_TYPES, { type: decoratedEnum.type });

        switch (decoratedEnum.type) {
          case 'DATE':
          case 'DATE_YEAR':
          case 'DATE_YEARMONTH':
          case 'DATE_MONTH':
          case 'DAY_OF_WEEK':
          case 'HOUR_OF_DAY':
          case 'HOUR_OF_DAY':
            if (visualDataType && _.isFunction(visualDataType.formatter)) {
              value = visualDataType.formatter({ value: value });
            }
            break;
        }

      } else {
        console.warn('Unable to identify cell enum');
        console.log(context);
      }

      return value;

    });

    // Export Data with warning and styles
    ExcelService.gridToXLSXSheetAgGrid(v.options.apiRef.agGridOptions, agGridExportParams);

    // Export data without warning or styles
    ExcelService.gridToXLSXSheetJS(v.options.apiRef.agGridOptions, agGridExportParams);

  }

}

**Comment by matthewpaulmcgowan** [comment] 2018-09-19 17:57
Working through the same issue here. Any idea when this will be fixed Ag-Grid?

**Comment by mbtakanov** [comment] 2018-11-01 10:28
Any update on the issue? I'm facing the same problem using v17.0.0.

**Comment by gportela85** [comment] 2018-11-01 15:32
This issue has been fixed in 19.1.1 as the grid exports a `.xlsx` file now.

**Closed by gportela85** 2018-11-01 15:32 UTC

**Comment by NessterGit** [comment] 2018-11-14 21:50
It seems like it's not fixed, even the examples on ag-grid website still have warnings on opening the Excel files (see https://www.ag-grid.com/javascript-grid-excel/#example-1-export-without-styles). 
I have pretty basic grids, just some row grouping, and I always get errors. Anyone else ?

**Comment by jmmurphy09** [comment] 2018-11-15 17:30
I agree that it's not fixed. I also get the errors when running any of the examples on the ag-grid webiste.

**Comment by gportela85** [comment] 2018-11-15 19:15
There was an issue with the `Export Without Styles` example that was fixed on 19.1.1. Right now I'm able to run all examples without any problems.
Can you share the error you are getting, browser version, etc..?

**Comment by jmmurphy09** [comment] 2018-11-15 19:32
Whenever I try opening the file I get a dialog that says "Excel found unreadable content in export.xlsx. Do you want to recover the contents of this workbook? If you trust the source of the workbook, click Yes." If I click yes, it opens fine shows another dialog that says "Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded."

It seems that it might be an Excel version problem. We are in the process of upgrading from Office 2010 to 2016 at my company right now. I am still on 2010 and see the error, but a coworker who has 2016 tried it and doesn't get the error.

**Comment by NessterGit** [comment] 2018-11-15 19:52
Same here, we are on older Office versions, tested on 2010 and 2007. Same
errors than Murphy reported.

Le jeu. 15 nov. 2018 14 h 32, jmmurphy09 <notifications@github.com> a
écrit :

**Comment by chaudhryaziz** [comment] 2018-11-30 21:07
Hi there, we are evaluating ag-grid enterprise and we are also seeing issues on Excel 2016(Mac) and Excel 2013(Windows)

In our case most of the data in the output Excel file is just plain missing. Looking at the data, it is clear that there is a pattern. Out sheet contains a combination of cells with alphanumeric values and other cells with just numeric values. The cells with Numeric values appear to come through just fine but all alphanumeric values disappear in the output Excel file. 

A not so great workaround I found is to specify the format to be xml. This produces an xml file that opens correctly in Excel. We then specify a filename of output.xls. This will force Excel to open it but then complain that the extension and filename dont match.

A fix would be greatly appreciated as this is the main feature my management wanted in our evaluation.

**Comment by DavidIMcIntosh** [comment] 2018-12-04 22:46
On Ag-grid 19.1.4, using Office 2010, getting same error as jmmurphy09.

**Comment by voyti** [comment] 2018-12-13 14:33
Same issue on ag-grid 19.1.4 using Excel for Mac 15.26. It seems that the file is formatted as intended after clicking through the dialogs

**Comment by mariusreusch** [comment] 2018-12-17 14:39
Same here with the following versions:

`"ag-grid-angular": "19.1.2",
    "ag-grid-community": "19.1.4",
    "ag-grid-enterprise": "19.1.4"`

and Office 2010.

As mentioned above, the error occurs even in the ag-grid sample (https://www.ag-grid.com/javascript-grid-excel/#example-1-export-without-styles).

It would be great, if this issue can be re-opened.

**Comment by juminoz** [comment] 2019-01-17 21:32
I still see the same issue on 19.1.4. When is the next release that will solve the issue?

**Comment by DavidIMcIntosh** [comment] 2019-01-17 21:36
Release 20.0.0 is already out and fixes the issue.

**Comment by juminoz** [comment] 2019-01-18 01:06
> Release 20.0.0 is already out and fixes the issue.

v20.0.0 has some major issues so far for me. I'm still trying to get everything working again and will try out the export feature. So far, the table doesn't even render properly after switching the version from 19.1.4 to 20.0.0.

**Comment by voyti** [comment] 2019-01-18 01:12
>  So far, the table doesn't even render properly after switching the version from 19.1.4 to 20.0.0.

Hate to go off-topic but had similar issues which turned out to be due to missing grid classes (which in my case mostly required changing uses of .ag-body to .ag-root-wrapper-body). Depending on your case this can obviously differ

**Comment by sameerhexagon** [comment] 2019-03-12 11:12
I am having the same issue. styles.xml generated by ag-grid does not meet requirements of newer Office versions.

**Comment by gportela85** [comment] 2019-03-12 18:30
@sameerhexagon What version of ag-grid are you using? All these issues with warnings have been patched.
So if you are seeing this with the latest version is probably worth filing a new issue.

**Comment by ludakhris** [comment] 2019-09-16 18:51
Why was this issue closed with no resolution?

**Comment by gportela85** [comment] 2019-09-16 19:03
@ludakhris The issue was fixed

**Comment by alexfriesen** [comment] 2019-12-20 13:37
I get this warning in Excel for Mac Version: 16.32. and AG-Grid Version 22.1.0.
Also the example at the bottom of https://www.ag-grid.com/javascript-grid-excel/#example-1-export-without-styles is broken

**Comment by kacpe-r** [comment] 2020-01-14 09:52
Issue still occurs.
ag-grid version: 22.1.1
Excel 2013.

**Comment by The-MAZZTer** [comment] 2020-03-03 16:19
I can reproduce this problem by taking a working grid with a working export that does NOT use excelStyles, and adding excelStyles. Then the problem manifests.

Specifically I force dataType for each column:

`	public excelStyles: ExcelStyle[] = [{
		id: "boolean",
		alignment: undefined,
		borders: undefined,
		font: undefined,
		interior: undefined,
		numberFormat: undefined,
		protection: undefined,
		dataType: "boolean"
	}, {
		id: "dateTime",
		alignment: undefined,
		borders: undefined,
		font: undefined,
		interior: undefined,
		numberFormat: undefined,
		protection: undefined,
		dataType: "dateTime"
	}, {
		id: "number",
		alignment: undefined,
		borders: undefined,
		font: undefined,
		interior: undefined,
		numberFormat: undefined,
		protection: undefined,
		dataType: "number"
	}, {
		id: "string",
		alignment: undefined,
		borders: undefined,
		font: undefined,
		interior: undefined,
		numberFormat: undefined,
		protection: undefined,
		dataType: "string"
	}];`

Then I bind this to the excelStyles property of the grid, and set the cellStyles property of my column definitions to the appropriate style.

After making these changes XSLX and XML files exported result in the corrutped message. I cannot open the XML files but Excel is able to recover XSLX files and the formatting seems to be how I want from a casual examination.

Unfortunately my dataset is massive so I am unable to analyze the XML/XSLX files to determine the problem.

**Comment by gallaouim** [comment] 2020-12-17 14:07
make sure that the cellClassName have only one Value , this will solve the Problem right now

**Comment by abhilashlr** [comment] 2022-03-19 06:18
We faced a similar issue on latest ag-grid package as well and the reason was that in the `exportDataAsExcel` we had a setting for `sheetName` that was dynamic. This dynamic value when it has `&` in it like for instance `Cricket & Football`, the excel file wouldn't open. Had to use a static string for now since I wonder what all scenarios and characters it would break for. 

If Ag-Grid team can fix this internally that would be great!

**Comment by syamanashi** [comment] 2022-04-22 13:15
@[The-MAZZTer](https://github.com/The-MAZZTer) Your reply saved me!  I spent a long time trying to find the cause of the corrupted Excel export files, and this was it.

For others who have this issue, my fix was removing this config property from every date column:

```
cellClass: 'dateUS',
```

**Comment by prashanth-lf** [comment] 2022-04-23 10:07
I am facing the issue still with the Ag-Grid version **22.1.0** on Mac monetary version **12.0.1**. After clicking 'Yes' from the Alert message shows `"We found a problem with some content in 'Export (15).xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes"`. I am able to see only the numerical dataTypes whereas strings values are disappeared. I can open the same exported XSLX sheet using the WPS office but not in Microsoft Excel on my machine and also it didn't cause any trouble while opening in Excel on a Windows machine. I even tried @The-MAZZTer's reply to fix it but no luck. Please help. Thank you.
