### ISSUE TITLE
Sticky grouping rows

### ISSUE THREAD

**Issue by kirylkastko** [ag-grid/ag-grid-enterprise#201] opened 2018-11-20 09:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
At the moment grouping rows scrolls as any other row in the table.

**Expected behavior**
I'd like to have a possibility to fix grouping row position on top while I scroll through the group.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
When there are a lot of rows in the group it is useful to see the header of the current group.

**Please tell us about your environment:**

* **ag-Grid-Enterprise version:** 18.1.1

* **Browser:** all

* **Language:** all

**Comment by ConorSheehan1** [comment] 2021-04-09 12:00
Dupe of https://github.com/ag-grid/ag-grid/issues/2292 ?
Being tracked by AG-463 at https://www.ag-grid.com/ag-grid-pipeline/
Doesn't seem to be prioritised :(

![Screenshot 2021-04-09 at 12 54 13](https://user-images.githubusercontent.com/16896053/114176616-4da56980-9933-11eb-9a2a-8eca7bdc5f14.png)

**Comment by merlijnbuit** [comment] 2022-05-31 10:17
The status is scheduled, when could we expect it? =)

**Comment by gportela85** [comment] 2022-05-31 14:19
Working on it right now, but still a work in progress. Stay tuned, it might come out in the next release.

**Closed by gportela85** 2022-05-31 14:19 UTC
