### ISSUE TITLE
ColumnsMenuTab Gets Removed After Refresh

### ISSUE THREAD

**Issue by FaitAccompli** [ag-grid/ag-grid-enterprise#276] opened 2022-01-20 07:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-enterprise/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

As mentioned in the documentation, 

> The menu will be displayed by default and will be made up of three panels

> The property menuTabs is an array of strings. The valid values are: 'filterMenuTab', 'generalMenuTab' and 'columnsMenuTab'.

<img width="195"  alt="image" src="https://user-images.githubusercontent.com/15321518/150285444-0b961a07-24f7-467b-ab28-4e4a35dcbb48.png">

On first load, the **columnsMenuTab** is visible. After a performing a refresh on the browser, the **columnsMenuTab** gets removed from the columns menu. 

This only happens on one page. The other pages work as expected, the columnsMenuTab is still there even after a refresh but for one page it gets removed after a refresh. 
 
![image](https://user-images.githubusercontent.com/15321518/150285836-609e423c-9f9f-4db1-9f41-27ce9da6472f.png)

**Expected behavior**

The **columnsMenuTab** should still be in the columns menu even after refreshing the browser. 

**Minimal reproduction of the problem with instructions**

Unfortunately, I can't share the code. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

     Operating System: Windows 10 Enterprise 64-bit (10.0, Build 19043)
     Package Manager: npm v8.1.2 
     JRE: node v16.13.0
     HTTP Server: localhost and nginx
     Frontend Framework: vue v^2.6.14 and nuxt v^2.15.8

* **ag-Grid-Enterprise version:** 2.0.X

    ag-Grid-Enterprise version: ^26.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

      Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    Typescript@4.5.4
    ES6/7

**Comment by kiril-matev** [comment] 2022-09-07 17:16
Hi @FaitAccompli,

Thank you for opening this github issue.

**You opened this issue in a legacy repository instead of the main one, which is why we've not responded to it earlier.**

When submitting this issue, you've not followed our bug report template. Specifically, you've not included a live plunker/standalone example reproducing the issue which is preventing us from investigating this further. It seems there's an important difference in your code that's causing this issue for one specific page. Having a reproduction example with this one page is crucial to investigating what the issue is.

As this issue was submitted a few months ago and many improvements were made to the grid in this time, please upgrade to the latest version of AG Grid and verify whether you can still see this issue. If you still have this issue with the latest version, please submit a new github issue in the main AG Grid repository with a reproduction example.

**We will now close this issue and archive this repository soon to avoid any further confusion. If you want to open any new issues, please report them under the main repository to ensure they are processed promptly and seen by the entire AG Grid community.**

**Closed by kiril-matev** 2022-09-07 17:16 UTC
